language: cpp
matrix:
  include:
    - os: osx
      sudo: false
      osx_image: xcode7.3

services:
  - docker

addons:
  apt:
    packages:
      - clang-format-3.9
      - p7zip-full

install: "./.travis-deps.sh"
script: "./.travis-build.sh"
after_success: "./.travis-upload.sh"

deploy:
  provider: releases
  api_key:
    secure: phVkqSaBgE8WmKHet1TdRrMDnenlWyFDJDTHQLr0NuCYXAYBGopbC9MqH3OxuEEO
  file_glob: true
  file: "artifacts/*"
  skip_cleanup: true
  on:
    tags: true
