language: cpp
matrix:
  include:
    - os: linux
      env: NAME="clang-format"
      dist: trusty
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - sourceline: 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main'
          packages:
            - clang-format-6.0
      script: "./.travis/clang-format/script.sh"
    - os: linux
      env: NAME="linux build"
      sudo: required
      dist: trusty
      services: docker
      addons:
        apt:
          packages:
            - p7zip-full
      install: "./.travis/linux/deps.sh"
      script: "./.travis/linux/build.sh"
      after_success: "./.travis/linux/upload.sh"
      cache: ccache
    - if: repo = citra-emu/citra AND branch = master AND type = push
      os: linux
      env: NAME="transifex push"
      sudo: required
      dist: trusty
      services: docker
      install: "./.travis/transifex/deps.sh"
      script: "./.travis/transifex/build.sh"
    - os: osx
      env: NAME="macos build"
      sudo: false
      osx_image: xcode9.2
      install: "./.travis/macos/deps.sh"
      script: "./.travis/macos/build.sh"
      after_success: "./.travis/macos/upload.sh"
      cache: ccache
    - os: linux
      env: NAME="linux build (frozen versions of dependencies without opencv)"
      sudo: required
      dist: trusty
      services: docker
      cache: ccache
      script: "./.travis/linux-frozen/build.sh"

deploy:
  provider: releases
  api_key:
    secure: psd//Bw/ForUB1L6YnBy3HOIsi5sCLXQX1OBC0qnS23XPN7sNKHdl/EsCPbBqyMjd9znXzp3siWIE3e7qXYTj948ypBdbB9PUpEIsw78xxQiox8yf8W/wQPs8PIMtsrq+vgFIE8mo3WirCUHu/9e5CGUSP9b9dGJXP3ONrnFHEqKuA4HMGqFX+JAzyZmSevzbKq71fpPya1OyORY1AQZVkP8REtTvVJywz3lf7CG1UmvETSnAA0qyJyQ5EM5Gtnbgaer9wDScT5jnb0nKm2+1Q+40/1GCqWT9ds6C/SY9Dh4xs0CPJNFyPeuNSk/yhBEpMcxYcZWzcro+gfoBL6I8GyKn1JF01HikEuHObq877iHThz9jjYq+pNVHtrSDOC3yP/W0du7dmkDlDtb17hcGkB3O7ybMsUqhxEwXiwdYOlnaV1dN3stw8Q2G0iAYkQZZegPWVOtUO4x3NojE0PtS6lzSWunPEWKBhncAAkpj7bO+uIL2EaL3bnWxfVG+oS9k/AG19/OP8vo8wzzdtOopsDucbHvRGz/MJ2mfIWWNirFWG+GBG8BCP9/eUibYY9y3FRHXQF9a0NzYJ1O3Pn45j28Bqyn/CrNEfUVLRchkkEklhj1OlWLBi5MLHKvi5Jxobbqi5ITuH8gQYbGBeqriKcvILSi/bGFSHjkNO3lblo=
  file_glob: true
  file: "artifacts/*"
  skip_cleanup: true
  on:
    $NAME =~ ^"linux build"|"macos build"$
