# shallow clone
clone_depth: 10

# skip tags
skip_tags: true

pull_requests:
  do_not_increment_build_number: true

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

os: Visual Studio 2017

platform:
  - x64

branches:
  only:
    - master

configuration:
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - ps: |
        cmd /C 'cmake -G "Visual Studio 15 2017 Win64" -DCITRA_USE_BUNDLED_QT=1 -DCITRA_USE_BUNDLED_SDL2=1 .. 2>&1 && exit 0'
  - cd ..

build_script:
  - ps: |
        # https://www.appveyor.com/docs/build-phase
        msbuild build/citra.sln /maxcpucount /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - ps: |
        $GITDATE = $(git show -s --date=short --format='%ad') -replace "-",""
        $GITREV = $(git show -s --format='%h')
        $RELEASE_DIST = "windows-x64"

        # Where are these spaces coming from? Regardless, let's remove them
        $BUILD_ZIP_NAME = "citra-windows-x64-$GITDATE-$GITREV.zip" -replace " ", ""

        # set the build name as env vars so the artifacts can upload them
        $env:BUILD = $BUILD_ZIP_NAME

        mkdir $RELEASE_DIST
        Copy-Item .\build\bin\release\* -Destination $RELEASE_DIST -Recurse
        Copy-Item .\license.txt -Destination $RELEASE_DIST
        Copy-Item .\README.md -Destination $RELEASE_DIST

        rm $RELEASE_DIST\*.pdb

        7z a -tzip $BUILD_ZIP_NAME $RELEASE_DIST\*

artifacts:
  - path: $(BUILD)
    name: build
    type: zip

deploy:
 - provider: Environment
   name: ghreleases
   on:
     branch: master
